---
name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - bionic
      - xenial
      - focal
  schedule:
    - cron: "10 1 * * 0"

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t docker-ansible .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged --tmpfs /tmp --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-container env TERM=xterm uptime

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: branch
      - name: Set Tag based on branch name
        id: setTag
        run: |
          if [[ "${{ steps.branch.outputs.branch }}" == "master" ]]; then
            echo "::set-output name=tag::latest"
          fi
          if [[ "${{ steps.branch.outputs.branch }}" != "master" ]]; then
            echo "::set-output name=tag::${{ steps.branch.outputs.branch }}"
          fi
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:${{ steps.setTag.outputs.tag }}