---
name: Build

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "10 1 * * 0"

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [latest, 22.04, 20.04, 18.04, 16.04]
    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t docker-ansible:${{ matrix.release }} --build-arg TAG=${{ matrix.release }} .

      - name: Run the built image.
        run: docker run --name test-container_${{ matrix.release }} -d --privileged --tmpfs /tmp --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible:${{ matrix.release }}

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-container_${{ matrix.release }} env TERM=xterm uptime

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        release: [latest, 22.04, 20.04, 18.04, 16.04]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          build-args: TAG=${{ matrix.release }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:${{ matrix.release }}